name: My First Workflow Run

on: [push]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-repo
      uses: actions/checkout@v5

    - name: greet_me
      run: echo "This is a test greeting run at $(date)"


    - name: run multiple commands
      run: |
        echo "Saying goodbye from ubuntu vm on $(date)"
        ls -la
        cat ./index.html
