name: greeter workflow

on: [ pull_request_target,push, issues ]

jobs:
    greeting:
        runs-on: ubuntu-latest
        permissions: 
            issues: write
            pull-requests: write
        steps:
            - uses: actions/first-interaction@v1
              with:
                  repo-token: ${{secrets.GITHUB_TOKEN}}
                  issues-message: "Message that will be displayed on first issue to user"
                  pr-message: "Message that will be displayed on users first PR"



